; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = release_wCOM

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = 
	ropg/ezTime@^0.8.3
	knolleary/PubSubClient@^2.8
	ayushsharma82/WebSerial
	ESP Async WebServer
lib_ignore = AsyncTCP_RP2040W

[env:debug]
debug_tool = esp-builtin
debug_load_mode = manual
build_type = debug
upload_protocol = esp-builtin
monitor_port = COM18
monitor_speed = 115200

[env:release_wOTA]
upload_protocol = espota
upload_port = irrig-leak.shencentral.net
monitor_port = COM18
monitor_speed = 115200

[env:release_wCOM]
upload_protocol = esptool
upload_port = COM18
upload_speed = 921600
monitor_port = COM18
monitor_speed = 115200

[env:i2c-scan]
build_src_filter = -<*> +<../test/i2c_scan.cpp>
lib_deps = 
lib_ignore = 
	WebSerial
	ESP Async WebServer
	AsyncTCP
	AsyncTCP_RP2040W
	ESPAsyncWebServer-esphome
upload_protocol = esptool
upload_port = COM18
upload_speed = 921600
monitor_port = COM18
monitor_speed = 115200
