; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = release_wOTA
;default_envs = release_wCOM

[env]
platform = espressif32
board = lilygo-t7-s3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
framework = arduino
lib_deps =
	ropg/ezTime@^0.8.3
	knolleary/PubSubClient@^2.8
	ayushsharma82/WebSerial
	ESP Async WebServer
lib_ignore = AsyncTCP_RP2040W

[env:debug]
debug_tool = esp-builtin
debug_load_mode = manual
build_type = debug
upload_protocol = esp-builtin
monitor_port = COM18
monitor_speed = 115200

[env:release_wOTA]
upload_protocol = espota
upload_port = irrig-leak.shencentral.net    ; check if this is correct if using IP!
monitor_port = COM18                        ; monitor port requires jtag serial port
monitor_speed = 115200

[env:release_wCOM]
upload_protocol = esp-builtin
upload_port = COM8
monitor_port = COM6                       ; monitor port requires jtag serial port
monitor_speed = 115200

[env:i2c-scan]
build_src_filter = -<*> +<../test/i2c_scan.cpp>
lib_deps =
lib_ignore = WebSerial, ESP Async WebServer, AsyncTCP, AsyncTCP_RP2040W, ESPAsyncWebServer-esphome
upload_protocol = esp-builtin
upload_port = COM8
monitor_port = COM6
monitor_speed = 115200